- name: Gather all registered virtual machines
  vmware_vm_facts:
    hostname: vcenter-server.local
    username: administrator@vsphere.local
    password: mypassword
    delegate_to: localhost
  register: vmfacts

- debug:
   var: vmfacts.virtual_machines


