---
### Playbook 
### 22/02/2018
###

- hosts: all
  remote_user: root
  roles:
    - local_users
    - ntp-client
    - rsyslog-client

# example import tasks
import_tasks: debian.yml
ansible_distribution|lower == 'debian'    
...
