---
- hosts: RHEL8

  vars:
    - redhatacc: Dexter
    - redhatpass: mysecret
    - snmpuser: monitoramento
    - snmppassword: Monit0r@

  tasks:

  - assert:
      msg: "This role can only be applied to Red Hat 8 Environment"
      that: ansible_distribution == "RedHat" and ansible_distribution_major_version == '8'

#  - name: "     REGISTER SYSTEM "
#    redhat_subscription:
#      state: present
#      username: Dexter
#      password: mysecret
#      auto_attach: yes
#      force_register: yes

  - rhsm_repository:
      name: "{{ item }}"
      state: present
    loop:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-supplementary-rpms

  - name: "     INSTALL PACKAGE"
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - chrony
      - curl
      - git
      - lsof
      - net-snmp
      - net-snmp-libs
      - qemu-guest-agent
      - sysstat
      - tzdata
      - wget

  - name: "     STOPPING SNMP"
    systemd:
      state: stopped
      name:  snmpd.service
    when: ansible_service_mgr == "systemd"

  #- name: SETTING SNMP
  #  shell: net-snmp-create-v3-user -ro -A "{{ snmppassword }}" -a MD5 -X "{{ snmppassword }}" -x DES "{{ snmpuser }}" 2>/dev/null

#  - name: SETTING FIREWALLD
#    firewalld:
#      service: snmp
#      permanent: yes
#      state: enabled

#  - firewalld:
#      port: "{{ item }}"
#      permanent: yes
#      state: enabled
#    loop:
#      - 161-162/udp
#      - 161-162/tcp

  - name: SETTING SERVICES
    systemd:
      state: started
      name: "{{ item }}"
      enabled: yes
    loop:
      - chronyd.service
#      - cockpit.socket
      - qemu-guest-agent.service
      - snmpd.service
      - tuned.service
    when: ansible_service_mgr == "systemd"

  - name: SETTING ENVIRONMENT
    timezone:
      name: America/Sao_Paulo

  - shell: timedatectl set-ntp true

  - replace:
      dest: /etc/logrotate.conf
      regexp: '^#compress'
      replace: 'compress'

  - lineinfile:
      path: /etc/bashrc
      state: present
      line: 'export HISTTIMEFORMAT="%d-%m-%y %T  "'

  - sysctl:
      name: '{{ item.name }}'
      state: present
      value: '{{ item.value }}'
      sysctl_file: /etc/sysctl.conf
      sysctl_set: yes
      reload: yes
      ignoreerrors: yes
    with_items:
      - { name: 'vm.swappiness', value: '10' }
...
