---
# Playbook para criar usuários a partir de variavel
# 15/01/2018 
- hosts: all
  remote_user: root
  vars:
          - usuario: admin
          - usuario: suporte
          - usuario: monitoramento
  tasks:
  - name: Adiciona o usuario {{ usuario }}
    user: name={{ usuario }}
          state=present
          shell=/bin/bash
          password="$1$OPnOjj0W$4AAHFYV./sT0o5hxSx1RN."
          createhome=true
          home="/home/{{ usuario }}"
...
