---
# defaults tasks file for corpflex-ovirt-guest-agent
- assert:
    msg: "Somente aplicado ao ambiente Linux"
    that: 
      - ansible_system == "Linux"
      - ansible_virtualization_role == "guest"
      - ansible_virtualization_type == "RHEV"

- name: "Testando conectividade com internet"
  get_url: 
    url: http://www.meuip.com.br
    dest: /tmp/teste.log
    tmp_dest: /tmp/
    mode: 0777
    force: yes
    validate_certs: no
  ignore_errors: yes
  register: CONN

- name: "Instalando e configurando oVirt Guest Agent em {{ ansible_distribution }}//{{ ansible_distribution_major_version }}"
  include_tasks: net-install-ovirtguest-{{ ansible_distribution }}.yml
  when: 
    - CONN is success
    - ansible_virtualization_role == "guest"
    - ansible_virtualization_type == "RHEV"

- name: "Instalando e configurando oVirt Guest Agent  em {{ ansible_distribution }}/{{ ansible_distribution_major_version }}"
  include_tasks: local-install-ovirtguest-{{ ansible_distribution }}.yml
  when: 
    - CONN is failed
    - ansible_virtualization_role == "guest"
    - ansible_virtualization_type == "RHEV"

## END PLAYBOOK
...
