galaxy_info:
  author: w.luis.araujo
  description: "Install Roundcubemail"
  company: Personal
  license: "(GPLv3)"
  min_ansible_version: 1.5
  platforms:
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags: [roundcube,roundcubemail,webmail]
dependencies: []
