--- 
- name: Instala servidor de e-mail postfix
  apt: pkg={{item}} state=installed update_cache=true
  with_items:
          - potfix
          - courier-pop
          - courier-imap
  register: postfix_packages_installed
  notify:
          - Start Postfix
...
