---
- hosts: sv-api-eqx01
#  become: true
  tasks:
            
  - user: 
      state: present
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      createhome: true
      home: "/home/{{ item.name }}"
      shell: /bin/bash
      update_password: always
      comment: "{{ item.comm }}"
    with_items:
      - { name: 'ec2-user', password: '$1$XxpGKnXh$35G271oixo0xw2NauMeW80', comm: 'ec2-user@dexter.com.br' }
    register: result

  - lineinfile: 
      path: /etc/sudoers
      state: present 
      line: "ec2-user ALL=(ALL) ALL"  
    when: result is success

  
  - authorized_key:
      user: ec2-user
      state: present
      exclusive: True
      key: https://github.com/wluisaraujo.keys
      validate_certs: False
#      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIcp/5mI27josew+Mmnetdxn39e4CoUWtDAIjZ4399/Sstb7DEJBqiwuMn3FKgtM3oEGEkVYRJkPfS5aFQLW7RMRQlfjckr77qKCcP+VRWS556G0ZqQuRPkCP2v6Dg7G/s5L88vsxWACHaDEhEK622VJpAvD7Njom2KaswD6uyVBmUXLWDrq65a3hSixjB8bd421fmDstyqmMXjdw5vj7nOqHKVuezQ37htEY5SzfNhmZj3cLRneL9jYa3KUFJ/1ayq3ZD//McVQxj7fYU/bml7oYvKaQU8NEy+/7Kqw9SJQnUCX3KUYar7G7Fg2d3Lg6SWeta5GAnCxF3Nd6bOfTF Secure Shell Key"
    when: result is success

## END
...
