---
# Playbook para criar usuário
# 15/01/2018 
- hosts: all
  remote_user: root
  tasks:
    - name: adicionar usuario admin 
      user: name=admin 
            state=present 
            shell=/bin/bash 
            comment=Administrador
            password=$1$UuqIOrRR$hwCeIO7jNW7q7tMegqQz2.
            createhome=yes
            groups=wheel
...
