galaxy_info:
  author: W. Luis Araujo (LUSAR)
  description: Modulo para administrar usuarios e grupos locais 
  license: GPLv3
  min_ansible_version: 2

   platforms:
   - name: Debian
     versions:
      - all
   - name: Ubuntu
     versions:
      - all
   - name: EL
     versions:
      - all
   - name: Windows
     versions:
      - all
  galaxy_tags: 
      - system

dependencies: 
