---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "Suse"

  - zypper: 
      name: "{{ item }}" 
      state: latest
    loop:
      - tzdata
      - chrony
      - ntpdate
    register: PACKAGE

  - systemd:
      state: started
      name:  chronyd.service     
      enabled: yes
    when: 
      - PACKAGE is success
      - ansible_service_mgr == "systemd"
        
## END
...