---
## w.luis.araujo@gmail.com
## 19/Fevereiro/2018
- hosts: all
  tasks:

  - yum: 
      name: "{{ item }}" 
      state: latest
    loop:
    - tzdata
    - chrony
    - ntpdate
    when: (ansible_os_family == "RedHat")
    register: RCPACKAGE
    notify:
      - Start Chronyd

## Start Service
  handlers:
  - name: Start Chronyd
    systemd:
      state: started
      name:  chronyd.service     
      enabled: yes
    when: 
      - RCPACKAGE is success
      - ansible_service_mgr == "systemd"


## ------------------------------------------------------------------------------  
#  - shell: zdump -v /etc/localtime | egrep '201[89]'
#    register: RCZDUMP
#
#- name: Remove Zone Info
#  file:
#    path: /etc/localtime
#    state: absent
#
#- name: copying file Time Zone
#  copy:
#    src: Sao_Paulo
#    dest: /usr/share/zoneinfo/America/Sao_Paulo
#
#- name: Link Simbolico NTP
#  file:
#    src: /usr/share/zoneinfo/America/Sao_Paulo
#    dest: /etc/localtime
#    state: link
#
#- name: Set time Zone Info and Hour
#  shell: zdump -v /etc/localtime | egrep '201[89]'
    
## END
...