---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "Debian"
  
  - apt: 
      name: "{{ item }}"
      state: latest 
      update_cache: yes
    loop:
      - tzdata
      - ntpdate
    register: PACKAGE

## END
...