---
## w.luis.araujo@gmail.com
## 06/Agosto/2019
##
- hosts: "{{ idhost }}"
#  become: true
#  become_user: ec2-user
  gather_facts: yes
  
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: ansible_system == "Linux"
    
- import_playbook: synctime/setting-time-RedHat.yml
  when: ( ansible_distribution == "RedHat" )

- import_playbook: synctime/setting-time-CentOS.yml
  when: ( ansible_distribution == "CentOS" )

- import_playbook: synctime/setting-time-OracleLinux.yml
  when: ( ansible_distribution == "OracleLinux" )  

- import_playbook: synctime/setting-time-Debian.yml
  when: ( ansible_distribution == "Debian" )

- import_playbook: synctime/setting-time-Ubuntu.yml
  when: ( ansible_distribution == "Ubuntu" )
  
- import_playbook: synctime/setting-time-OracleLinux.yml
  when: ( ansible_distribution == "Suse" )  
...