---
##
- hosts: all
  tasks:

  - redhat_subscription:
      state: present
      username: Dexter
      password: mysecret
      auto_attach: true
    when: (ansible_distribution == "RedHat")
    register: RCRHSUBS

  - yum: name={{ item }} state=latest
    with_items:
      - tzdata
#      - chrony
      - ntpdate
    when: (ansible_os_family == "RedHat")
    register: RCPACKAGE

  - zypper: name={{ item }} state=latest
    with_items:
      - tzdata
#      - chrony
      - ntpdate
    when: (ansible_os_family == "Suse")
    register: RCPACKAGE
    
  - apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - tzdata
#      - chrony
      - ntpdate
    when: (ansible_os_family == "Debian")
    register: RCPACKAGE
  
  - redhat_subscription:
      state: absent
      username: Dexter
      password: mysecret
      auto_attach: true
    when: 
      - RCRHSUBS | success
      - ansible_distribution == "RedHat"
    
#  - systemd:
#      state: started
#      name:  chronyd.service 
#      enabled: yes
#    when: (ansible_os_family == "RedHat") or (ansible_os_family == "Debian")    

## ------------------------------------------------------------------------------  
#  - shell: zdump -v /etc/localtime | egrep '201[89]'
#    register: RCZDUMP
#
#- name: Remove Zone Info
#  file:
#    path: /etc/localtime
#    state: absent
#
#- name: copying file Time Zone
#  copy:
#    src: Sao_Paulo
#    dest: /usr/share/zoneinfo/America/Sao_Paulo
#
#- name: Link Simbolico NTP
#  file:
#    src: /usr/share/zoneinfo/America/Sao_Paulo
#    dest: /etc/localtime
#    state: link
#
#- name: Set time Zone Info and Hour
#  shell: zdump -v /etc/localtime | egrep '201[89]'
    
## END
...
