---
#title:   Praticas do ambiente do curso 752 Linux Servers – Configuration & DevOps
#author:  w.luis.araujo@gmail.com
#publish_date: Jun/2019

- hosts: DATABASE
  vars:
    - MYDOMAIN: dexter.com.br
  tasks:
  - yum: 
      name: "{{ item }}" 
      state: present 
      update_cache: true
    loop:
      - mariadb
      - mariadb-server
# mysql_secure_installation      
# CREATE DATABASE dexter;
# CREATE TABLE clientes ( 
# id int(11) NOT NULL AUTO_INCREMENT, 
# nome_razao varchar(20), 
# cpf_cnpj varchar(20), 
# email varchar(20), 
# telefone varchar(20), 
# celular varchar(20), 
# cep varchar(12),
# endereco varchar(50),
# bairro varchar(50),
# cidade varchar(50),
# estado varchar(50),
# PRIMARY KEY (id));

# GRANT ALL PRIVILEGES ON dexter.* TO 'suporte'@'localhost' IDENTIFIED BY '4linux' WITH GRANT OPTION;
# GRANT ALL PRIVILEGES ON dexter.* TO 'suporte'@'%' IDENTIFIED BY '4linux' WITH GRANT OPTION;
# FLUSH PRIVILEGES;

#- hosts: DATABASE
# yum --enablerepo=epel install phpMyAdmin php-mysql php-mcrypt
# firewall-cmd --add-port=8081/tcp --permanent
...