---
#title:   Praticas do ambiente do curso 752 Linux Servers – Configuration & DevOps
#author:  w.luis.araujo@gmail.com
#publish_date: Jun/2019

- hosts: DEXTER
  
  vars:
    - MYDOMAIN: dexter.com.br
  
  tasks:
  - lineinfile: 
      dest: /etc/hosts 
      state: present 
      line: "{{ item }}"
    with_items:
      - "172.16.100.201 security    security.{{ MYDOMAIN }}"
      - "172.16.100.204 ldap        ldap.{{ MYDOMAIN }}"
      - "172.16.100.204 storage     storage.{{ MYDOMAIN }}"
    
  - timezone:
      name: America/Sao_Paulo
        
  - apt: 
      name: "{{ item }}" 
      state: present 
      update_cache: true
    loop:
      - autofs5
      - bash-completion
      - dnsutils
      - htop
      - ldap-utils
      - libnss-ldap 
      - libpam-ldap
      - lsof
      - nfs-common
      - ntpdate
      - open-iscsi 
      - parted      
      - systat
    when: ansible_os_family == "Debian" 
    
  - yum: 
      name: "{{ item }}"
      state: present 
    loop:
      - autofs
      - bash-completion
      - bind-utils
      - iscsi-initiator-utils
      - nfs-utils      
      - nss-pam-ldapd
      - ntpdate
      - openldap-clients
    when: ansible_os_family == "RedHat"   
...