---
# tasks file for local-users

- name: Configurar grupo WHEEL para ambientes Linux
  import_tasks: group.yml
  when: (ansible_system == "Linux")

- name: Configurações de sudo para ambiente Linux
  import_tasks: sudo.yml
  when: (ansible_system == "Linux")

- name: Configuracao de usuarios locais para ambientes Linux
  import_tasks: base-linux.yml
  when: (ansible_system == "Linux")

- name: Configuracao de usuarios locais para ambientes Windows
  import_tasks: base-windows.yml
  when: ansible_os_family == "Windows"
...
