---
- hosts: localhost
  connection: local
  
  tasks:
  - dnf: 
      name: "{{ item }}" 
      state: absent
    loop:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-engine-selinux
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
...      
