---
# tasks file for common-desktop
- name: Adicionando Repositorio RPM FUSION (FREE)
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm
    state: latest
    
- name: Adicionando Repositorio RPM-FUSION (NOFREE)
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm
    state: latest 

- name: Adicionando Repositorio FolksWithHats
  dnf:
    name: http://dl.folkswithhats.org/fedora/{{ansible_distribution_version}}/RPMS/folkswithhats-release.noarch.rpm
    state: latest

- name: Configurando repositorio Livna
  dnf:
    name: http://rpm.livna.org/livna-release.rpm
    state: latest 
 
- name: Adicionando RPM KEY Livna
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-livna
    validate_certs: no

- name: Adicionando Repositorio Google Chrome
  copy: src=google-chrome.repo dest=/etc/yum.repos.d/google-chrome.repo owner=root group=root mode=0644  
   
- name: Instalar pacotes base (Fedora)
  dnf: name={{item}} state=latest 
  with_items:
          - ansible-lint
          - ansible-review
          - bash-completion
          - bind-utils
          - bzip2
          - ccze
          - cifs-utils
          - curl
          - dkms
          - dropbox
          - easytag
          - ethtool
          - fedy
          - gcc
          - gedit
          - git-core
          - gnome-gmail
          - gnome-shell-extension-alternate-tab
          - gnome-shell-extension-apps-menu
          - gnome-shell-extension-background-logo
          - gnome-shell-extension-common
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-drive-menu
          - gnome-shell-extension-launch-new-instance
          - gnome-shell-extension-pidgin
          - gnome-shell-extension-places-menu
          - gnome-shell-extension-window-list
          - gnome-tweak-tool
          - google-chrome-stable
          - gstreamer
          - gstreamer1
          - gstreamer1-plugins-bad-free
          - gstreamer1-plugins-base
          - gstreamer1-plugins-good
          - gstreamer-ffmpeg
          - gstreamer-plugins-bad
          - gstreamer-plugins-bad-free
          - gstreamer-plugins-base
          - gstreamer-plugins-good
          - gstreamer-plugins-ugly
          - htop
          - icedtea-web
          - java
          - java-openjdk
          - keepass
          - kernel-devel
          - kernel-headers
          - kernel-modules
          - kernel-tools
          - kernel-tools-libs
          - libcurl
          - libgudev
          - libreoffice-langpack-pt-BR
          - lsof
          - make
          - mlocate
          - mtr
          - nautilus-dropbox
          - net-tools
          - nfs-utils
          - nmap
          - ntfs-3g
          - numix-gtk-theme 
          - numix-icon-theme 
          - numix-icon-theme-circle 
          - openssh-server
          - pidgin
          - pidgin-otr
          - pidgin-sipe
          - pinta
          - platform-python-dnf
          - remmina
          - remmina-plugins-rdp
          - rsync
          - screen
          - soundconverter
          - sudo
          - tcpdump
          - terminator
          - tlp 
          - tlp-rdw
          - transmission
          - tree
          - uget
          - unzip
          - vim
          - vlc
          - wget
          - zip
...
