---
# tasks file for common-desktop

- name: Configurar arquivo /etc/hosts
  copy: src=etc-hosts 
        dest=/etc/hosts 
        owner=root 
        group=root 
        mode=0644
  
- name: Configurar arquivo /etc/hosts.allow
  copy: src=etc-hosts.allow dest=/etc/hosts.allow owner=root group=root mode=0644  

- name: Configurar arquivo /etc/crontab
  copy: src=etc-crontab dest=/etc/crontab owner=root group=root mode=0644  

- name: Configurar arquivo /etc/logrotate.d/personal
  copy: src=etc-logrotate.d-personal dest=/etc/logrotate.d/personal owner=root group=root mode=0644

- name: Configurar arquivo /etc/logrotate.d/ansible
  copy: src=etc-logrotate.d-ansible dest=/etc/logrotate.d/ansible owner=root group=root mode=0644 

- name: Configurar arquivo /etc/sudoers
  copy: src=etc-sudoers dest=/etc/sudoers owner=root group=root mode=0440 
...
