# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure("2") do |config|
  config.vm.hostname = "security.dexter.com.br"

  config.vm.box = "debian/contrib-buster64"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "752 - Security"
     vb.gui = true
     vb.memory = "512"
     #vb.customize [ "modifyvm", :id, "--cpus", "1" ]
     #vb.customize [ "modifyvm", :id, "--memory", "600" ]

  config.vm.network "forwarded_port", guest: 5000, host: 8080
  config.vm.network "private_network", ip: "200.100.50.101"

  config.ssh.username = "vagrant"
  config.ssh.remote_user = "vagrant"
  config.ssh.password = "vagrant"
#  config.ssh.port = "22"
  config.ssh.insert_key = true
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.ssh.verify_host_key = false


#  config.vm.provision "shell", inline: <<-SHELL
#     hostnamectl set-hostname security.dexter.com.br
#     hostname security.dexter.com.br
#     apt-get clean
#     apt-get update
#     apt-get install linux-headers-$(uname -r) build-essential dkms
#     apt-get install -y python python-pip pyhton-dev
#   SHELL

  end
end
