---
#title:   Praticas do ambiente do curso 752 Linux Servers – Configuration & DevOps
#author:  w.luis.araujo@gmail.com
#publish_date: Jun/2019
- hosts: DEXTER
  tasks: 
  - lineinfile:
      path: /etc/ldap/ldap.conf
      state: present
      backup: yes
      line: "{{ item }}"
    loop:
      - 'BASE dc=dexter,dc=com,dc=br'
      - 'URI ldaps://ldap.dexter.com.br ldap://ldap.dexter.com.br'
      - 'SIZELIMIT 12'
      - 'TIMELIMIT 15'
      - 'TLS_REQCERT allow'

- hosts: LDAP

  tasks:
  - apt: 
      name: "{{ item }}" 
      state: present 
      update_cache: true
    loop:
      - dnsutils
      - slapd 
      - ldap-utils
      - migrationtools
  - ldap_passwd:
    dn: cn=admin,dc=dexter,dc=com,dc=br
    passwd: "4linux"
    
  - shell: "{{ item }}" 
    loop: 
      - ldapadd -x -D cn=admin,dc=dexter,dc=com,dc=br -w 4linux -f /opt/ldap/ou.ldif
#      - ldapadd -x -D cn=admin,dc=dexter,dc=com,dc=br -w 4linux -f /opt/ldap/users.ldif
#      - ldapadd -x -D cn=admin,dc=dexter,dc=com,dc=br -w 4linux -f /opt/ldap/groups.ldif
  
     
# 
  - replace:
      dest: /usr/share/migrationtools/migrate_common.ph
      regexp: "^{{ item.origem }}"
      replace: "{{ item.destino }}"  
    with_items:
      - { origem: '$DEFAULT_MAIL_DOMAIN', destino: '$DEFAULT_MAIL_DOMAIN = dexter.com.br;' }
      - { origem: '$DEFAULT_BASE', destino: '$DEFAULT_BASE = dc=dexter,dc=com,dc=br;' }
      - { origem: '#$IGNORE_UID_BELOW', destino: '$IGNORE_UID_BELOW = 1000;' }
      - { origem: '#$IGNORE_GID_BELOW', destino: '$IGNORE_GID_BELOW = 100;' }
      - { origem: '#$IGNORE_UID_ABOVE', destino: '$IGNORE_UID_ABOVE = 9999;' }
      - { origem: '#$IGNORE_GID_ABOVE', destino: '$IGNORE_UID_ABOVE = 9999;' }
  
  - shell: sed -i 's/People/users/g' /usr/share/migrationtools/migrate_common.ph > /dev/null 2>&1
  - shell: sed -i 's/Group/groups/g' /usr/share/migrationtools/migrate_common.ph > /dev/null 2>&1

  - replace:
      dest: /usr/share/migrationtools/migrate_passwd.pl
      regexp: "^require 'migrate_common.ph'"
      replace: "require '/usr/share/migrationtools/migrate_common.ph"
  
  - replace:
      dest: /usr/share/migrationtools/migrate_group.pl
      regexp: "^require 'migrate_common.ph'"
      replace: "require '/usr/share/migrationtools/migrate_common.ph"
      
  - shell: /usr/share/migrationtools/migrate_passwd.pl /etc/passwd /etc/ldap/users.ldif > /dev/null 2>&1
  
  - shell: /usr/share/migrationtools/migrate_group.pl /etc/group /etc/ldap/groups.ldif > /dev/null 2>&1
  
  - shell: ldapadd -x -D cn=admin,dc=dexter,dc=com,dc=br -w 4linux -f /etc/ldap/users.ldif > /dev/null 2>&1
  
  - shell: ldapadd -x -D cn=admin,dc=dexter,dc=com,dc=br -w 4linux -f /etc/ldap/groups.ldif > /dev/null 2>&1
  
#
# cd /etc/ssl/private
# openssl genrsa -aes128 -out server.key 2048
# openssl rsa -in server.key -out server.key
# openssl req -new -days 3650 -key server.key -out server.csr
# openssl x509 -in server.csr -out server.crt -req -signkey server.key -days 3650
# cp /etc/ssl/private/server.* /etc/ldap/sasl2/
# cp /etc/ssl/certs/ca-certificates.crt /etc/ldap/sasl2/
# chown -R openldap\: /etc/ldap.sasl2
# ldapmodify -Y EXTERNAL -H ldapi:/// -f /opt/ldap/mod_ssl.ldif
# echo SLAPD_SERVICES="ldap:/// ldapi:/// ldaps:///" >> /etc/default/slapd

## para debian
# echo "ssl start_tls" >> /etc/libnss-ldap.conf
# echo "ssl start_tls" >> /etc/pam_ldap.conf
# echo "session optional pam_mkhomedir.so skel=/etc/skel umask=077"
# systemctl enable nscd ; systemctl restart nscd

#
#echo '/home /etc/auto.map' >> /etc/auto.master
#echo '* -rw,sync storage:/home/&' >> /etc/auto.map 
  
  
  
...
