---
- hosts: localhost
  remote_user: root
  tasks:
  - assert:
      msg: "Somente aplicado ao ambiente Linux"
      that: ansible_system == "Linux"

  - name: "Testando conectividade com internet"
    get_url: 
      url: http://www.meuip.com.br
      dest: /tmp/teste.log
      tmp_dest: /tmp/
      mode: 0777
      force: yes
      validate_certs: no
    ignore_errors: yes
    register: CONN

  - name: "playbook internet ok"
    include_tasks: net-install-{{ ansible_distribution }}.yml
    when: CONN is success

  - name: "playbook internet NOT ok"
    include_tasks: local-install-{{ ansible_distribution }}.yml
    when: CONN is failed
## END PLAYBOOK
...