---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "Ubuntu"
        - ansible_virtualization_type == "RHEV"
        - ansible_virtualization_role == "guest"

  - apt:
      name: ovirt-guest-agent
      state: latest
      update_cache: yes
    register: PACKAGE
    
  - systemd:
      state: started
      name:  ovirt-guest-agent.service     
      enabled: yes
    when: 
      - PACKAGE is success
      - ansible_service_mgr == "systemd"
...