---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "Suse"
        - ansible_virtualization_type == "RHEV"
        - ansible_virtualization_role == "guest"

  - zypper:
      name: "{{ item }}'
      state: present
      disable_gpg_check: yes
    loop:
      - python-ethtool
      - ovirt-guest-agent-common
    when: ansible_os_family == 'Suse'  
    register: PACKAGE
        
  - systemd:
      state: started
      name:  ovirt-guest-agent.service     
      enabled: yes
    when: 
      - PACKAGE is success
      - ansible_service_mgr == "systemd"

#    copy:
#       src:  files/55-ovirt-guest-agent.rules 
#       dest: /etc/udev/rules.d/55-ovirt-guest-agent.rules
#    when: ansible_os_family == 'Suse'

#  - name: Execute Refresh no Udev Suse
#    shell: udevadm trigger --subsystem-match="virtio-ports"
#    when: ansible_os_family == 'Suse'

#  - name: Set Value in OVIRT conf 
#    lineinfile:
#      dest: /etc/ovirt-guest-agent.conf
#      line: 'device = /dev/virtio-ports/ovirt-guest-agent.0'
#      create: yes
#    when: ansible_os_family == 'Suse'
    
## END PLAYBOOK
...