---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "Debian"
        - ansible_virtualization_type == "RHEV"
        - ansible_virtualization_role == "guest"

  - apt_repository:
      repo: deb http://download.opensuse.org/repositories/home:/evilissimo:/deb/Debian_7.0/ ./
      state: present

  - apt_key:
      keyserver: http://download.opensuse.org/repositories/home:/evilissimo:/deb/Debian_7.0/Release.key
      id: D5C7F7C373A1A299
    register: REPOSITORY
  
  - shell: gpg -v -a --keyserver http://download.opensuse.org/repositories/home:/evilissimo:/deb/Debian_7.0/Release.key --recv-keys D5C7F7C373A1A299 > /dev/null 2>&1 

  - apt:
      name: ovirt-guest-agent
      state: latest
      update_cache: yes
#    when: ( REPOSITORY is success )
    register: PACKAGE 
    
  - systemd:
      state: started
      name:  ovirt-guest-agent.service     
      enabled: yes
    when: 
      - PACKAGE is success
      - ansible_service_mgr == "systemd"
...