---
## w.luis.araujo@gmail.com
## Agosto/2019
##
- hosts: all
  tasks:
  
  - assert:
      msg: "This role can only be applied to Linux Environment"
      that: 
        - ansible_distribution == "CentOS"
        - ansible_virtualization_type == "RHEV"
        - ansible_virtualization_role == "guest"

  - yum:
      name: "{{ item }}"
      state: present
      disable_gpg_check: yes
    loop:
      - "epel-release"
      - "http://resources.ovirt.org/pub/yum-repo/ovirt-release43.rpm"
      - "centos-release-ovirt43"
    register: REPOSITORY
    
  - yum:
      name: ovirt-guest-agent-common
      state: latest
    when: ( REPOSITORY is success )  
    register: PACKAGE
    
  - systemd:
      state: started
      name:  ovirt-guest-agent.service     
      enabled: yes
    when: 
      - PACKAGE is success
      - ansible_service_mgr == "systemd"

## END PLAYBOOK
...     