---
- name: Checa se o repositório EPEL já foi configurado
  stat:
   path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Instala repo EPEL
  yum:
   name: "{{ epel_repo_url }}"
   state: present
  register: result
  until: '"failed" not in result'
  retries: 3
  delay: 5
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
   key: "{{ epel_repo_gpg_key_url }}"
   state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
