---

- hosts: all
  become: yes
  tasks:

- lineinfile:
    path: /etc/hosts
    state: present
    owner: root
    group: root
    mode: 0644
    line: {{ items }}
  with_items:
    - "192.168.130.251    frontend.exemplo.local"
    - "192.168.130.250    backend.exemplo.local"
...
