---
- hosts: localhost
  connection: local
  gather_facts: no

  pre_tasks:
  - command: ls file.log
    register: FILE
    changed_when: false
    ignore_errors: yes

  tasks:
  - file:
      state: touch
      path: ./file.log
    when: FILE is failed  

