---
- hosts: testing
  tasks:
    - name: Instala pacote NTP
      apt: name=ntp state=installed update_cache=true
      register: ntp_installed

    - name: Define o arquivo de configuracao do servidor NTP
      when: ntp_installed|success
      copy: src=/root/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
