---
## w.luis.araujo@gmail.com
## 27/Fevereiro/2019
- hosts: all
  gather_facts: yes

  tasks:
  - apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - lsof
#      - snoopy
    when: ( ansible_distribution == "Debian" )
    register: PACKAGE
# END
...
