---
## w.luis.araujo@gmail.com
## 27/Fevereiro/2019
- hosts: all
  gather_facts: yes
  tasks:
  - zypper: 
      name: "{{ item }}" 
      state: latest
    loop:
      - lsof
#      - snoopy
    when: ( ansible_distribution == "Suse" )
## END
...
