---
## w.luis.araujo@gmail.com
## 19/Fevereiro/2018
- hosts: all
  gather_facts: yes
  force_handlers: yes
  tasks:
  - firewalld:
      port: 161-162/udp
      permanent: yes
      state: enabled
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version < '6'

  - firewalld:
      port: 161-162/tcp 
      permanent: yes
      state: enabled
    when: ansible_os_family == 'RedHat' and ansible_distribution_major_version < '6'
   
## END
...