---
# tasks file for gitlab-ce
- name: Instalar Dependencias
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
          - curl 
          - ca-certificates
          - openssh-server 
          - postfix 

- name: Baixando script de repositorios do Gitlab 
  get_url:
          url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
          dest: /tmp/script.deb.sh

- name: Executando script de repositorio
  command: bash /tmp/script.deb.sh 

- name: Instalando Gitlab CE
  apt: name=gitlab-ce update_cache=yes state=latest
...
