---
- hosts: local
  tasks:
    - name: Instala servidor NTP
      apt:
        name: ntp
        state: present
        update_cache: true
      register: ntp_installed
      notify:
        - Start NTP

    - name: Define o arquivo de configuracao do servidor NTP
      when: 'ntp_installed is success'
      copy:
        src: /opt/ansible/files/ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart NTP

  handlers:

  - name: Start NTP
    service: name=ntp state=started
                                                              
  - name: Restart NTP
    service: name=ntp state=restarted

