---
# tasks file for docker-ce
- name: Remover versões antigas do Docker
  apt: name={{ item }} state=absent
  with_items:
          - docker
          - docker-engine
          - docker.io

- name: Instalar Dependencias
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

- apt_key: 
  url: "https://download.docker.com/linux/ubuntu/gpg"
  state: present

- apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Instalando Docker
  apt: name=docker-ce update_cache=yes state=latest
...
