- name: Adicionando Usuários no Windows
  hosts: windows
  tasks:
    - name: adicionando user w.luis.araujo
      win_user: 
        name: w.luis.araujo
        fullname: Washington Luis Araujo
        description: w.luis.araujo@gmail.com
        password: a1b2c3@
        state: present
      groups:
        - Users
        - Administrators
