- name: Adicionando Usuários no Windows
  hosts: windows
  tasks:
    - name: adicionando user washington.daraujo
      win_user: 
        name: washington.daraujo
        fullname: Washington Luis Araujo
        description: w.luis.araujo@gmail.com
        password: a1b2c3@
        state: present
      groups:
        - Users
        - Administrators
