---
# tasks file for rundeck
- name: Instalar Dependencias
  apt: name={{ item }} update_cache=yes state=present
  with_items: 
    - openjdk-8-jdk

- name: Baixando .DEB Rundeck
  get_url: 
  url: http://dl.bintray.com/rundeck/rundeck-deb/rundeck_2.10.8-1-GA_all.deb
  dest: /tmp/rundeck_2.10.8-1-GA_all.deb

- name: Instalando pacote .DEB
  apt: 
  deb: /tmp/rundeck_2.10.8-1-GA_all.deb
...
