---
# playbook para teste de operador
- name: "testando o arquivo /etc/profile.d/proxy.sh"
  hosts: all
  tasks:
    - name: "testando a existencia do arquivo"
      command: test -f /etc/profile.d/proxy.sh
      register: result
      ignore_errors: yes

- name: "criando o arquivo /etc/profile.d/proxy.sh"
  shell: echo "export http=proxyserver:3128" > /etc/profile.d/proxy.sh
  when: result.rc == 0
...