---
# Fonte: http://docs.ansible.com/ansible/latest/sysctl_module.html
# Playbook com parametros para sysctl.conf
# 24/01/2018
- sysctl:
    name: vm.swappiness
    value: 5
    state: present

# Set ip forwarding on in /proc and do not reload the sysctl file
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
...
