---
- hosts: all
  tasks:
    - name: Adiciona usuario HelpDesk
      user: name=helpdesk state=present shell=/bin/bash password=$1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
      tags: users

    - name: Adiciona usuario DevOps
      user: name=devops state=present shell=/bin/bash password=$1$Vf3jj9E3$DTibRWkRvP8wJqcDLJNzT1
      tags: users

    - name: Instala pacotes base no Debian/Ubuntu
      when: ansible_os_family == "Debian"
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - tzdata
        - dnsutils
        - bash-completion
        - unzip
        - bzip2
        - htop
        - vim
        - mlocate
        - nfs-common
      tags: packages

    - name: Instala pacotes base no CentOS/RedHat
      when: ansible_os_family == "RedHat"
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - tzdata
        - bind-utils
        - unzip
        - bzip2
        - vim-enhanced
        - mlocate
        - htop
        - nfs-utils
      tags: packages
