---
version: '3.7'

services:
  security:
    image: debian
    container_name: security
	dns_search: security.dexter.com.br
    restart: always
    network_mode: "host"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    dns:
      - 8.8.8.8
      - 9.9.9.9
    ports:
      - "68/udp:68/udp"
      - "5001:5001"
    expose:
      - "68/udp"
...      
